### ISSUE TITLE
[AJUSTES] Tela How to Travel

### ISSUE THREAD

**Issue by brunacabeco** [germanodusha/roam#106]
Como é pra ser:
<img width="699" alt="Captura de Tela 2021-07-01 às 15 36 51" src="https://user-images.githubusercontent.com/82957414/124321907-ddcf0580-db54-11eb-86bb-5038f20a7113.png">

- [x] aumentar peso da fonte do título
- [x] aumentar espaçamento entre letras da fonte do título
- [x] aumentar peso de WASD e USE YOUR MOUSE....
- [x] descer mais um pouco pra perto da borda do dox o 'explore the maze in 360..'
- [x] blur no titulo e fontes das caixas

Como está:
<img width="1276" alt="Captura de Tela 2021-07-02 às 16 40 10" src="https://user-images.githubusercontent.com/82957414/124321834-be37dd00-db54-11eb-9e8d-8eedc14412bc.png">

**Comment by guigallo** [comment]
@brunacabeco 'how to travel in' já esta com o maior peso'
