### ISSUE TITLE
[AJUSTES] Melhor proporções da Tela Inicial

### ISSUE THREAD

**Issue by brunacabeco** [germanodusha/roam#107]
Melhorar proporção

- [x] aumentar bastante tamanho da fonte para o tamanho de tela intermediário
- [x] subir mais (deixar bem abaixo de ROAM) a frase ' press F to...)

<img width="341" alt="Captura de Tela 2021-07-02 às 16 59 32" src="https://user-images.githubusercontent.com/82957414/124323094-140d8480-db57-11eb-9f1d-39c23abbdf2e.png">

**Comment by guigallo** [comment]
![image](https://user-images.githubusercontent.com/17219256/124355354-0a336200-dbe7-11eb-8888-5dc64c3dab3e.png)

**Comment by guigallo** [comment]
![image](https://user-images.githubusercontent.com/17219256/124355383-2cc57b00-dbe7-11eb-820e-4288eff39304.png)
