### ISSUE TITLE
[HUD] Ícone conteúdos extras visitados

### ISSUE THREAD

**Issue by brunacabeco** [germanodusha/roam#14]
## 0. HUD
 
 **Conteúdos extra visitados (0.5)**
 
<img width="128" alt="Captura de Tela 2021-06-16 às 15 23 43" src="https://user-images.githubusercontent.com/82957414/122272391-e23dc200-ceb6-11eb-9504-53313115e36c.png">

- [x] símbolo

- [x] número
  - fonte: BreatheFireli https://drive.google.com/file/d/1KIrZoR4k-GJUeJ6uXIW_kB5YZDsd_MEh/view?usp=sharing
  - cor: vermelho
 
- [x] Incluir barra de total x visitados. Ex: 2/40 (visitado 2 objetos de 40). Ainda estamos aguardando do clientes quantos de cada um (objetos e conteúdos extras) estarão espalhados pelo ambiente. 
 
- [x] função: aumenta 1 quando visita conteúdo extra (das nuvens)

**Comment by guigallo** [comment]
foi implementado contador de conteúdo principal e extra
