### ISSUE TITLE
[Media Center] Trocar frase rodapé: Press F for scroll

### ISSUE THREAD

**Issue by brunacabeco** [germanodusha/roam#44]
## 4. Media Center: frase rodapé

**Trocar frase atual por: press for F for scroll**

como está atualmente:
<img width="264" alt="Captura de Tela 2021-06-28 às 17 48 24" src="https://user-images.githubusercontent.com/82957414/123702423-7f92e180-d839-11eb-8522-80cd509a1790.png">

- [x] frase: " Use for scroll"
  - fonte: Allan Regular https://drive.google.com/file/d/1toZ4mgcJgDCZE1No3aDX9YrAvjPwb--a/view?usp=sharing

- [x] botões F
  - fonte:ARIAL

ref:
<img width="255" alt="Captura de Tela 2021-07-01 às 09 46 30" src="https://user-images.githubusercontent.com/82957414/124126590-34ebb200-da51-11eb-9f5c-7238b8678a77.png">
<img width="388" alt="Captura de Tela 2021-07-01 às 09 46 07" src="https://user-images.githubusercontent.com/82957414/124126600-374e0c00-da51-11eb-9614-cf91e88c3363.png">
<img width="305" alt="Captura de Tela 2021-07-01 às 09 45 52" src="https://user-images.githubusercontent.com/82957414/124126616-3b7a2980-da51-11eb-886e-dbd238a74089.png">

---
tela inteira: 
<img width="484" alt="Captura de Tela 2021-06-19 às 17 03 57" src="https://user-images.githubusercontent.com/82957414/122654230-6b0b6680-d120-11eb-8079-7af2f4cb71b0.png">

**Comment by guigallo** [comment]
@brunacabeco me parece que a fonte do 'F' é dungeon, nao Allan bold

**Comment by brunacabeco** [comment]
> @brunacabeco me parece que a fonte do 'F' é dungeon, nao Allan bold

Na verdade, todos esses botões são com a fonte Arial bem grossa no design.

**Comment by brunacabeco** [comment]
@guigallo coloquei a referência ali. ficou confuso mesmo. Essa correção de todos os botões está na issue #67. Se for algo que você corrige e aplica pra todos...já foi poder fechar as duas :)

**Comment by guigallo** [comment]
usar arial e arrumar proporcoes

**Comment by guigallo** [comment]
'press' ao invés de 'use'
