### ISSUE TITLE
[CONTROLE] Definir quais/uso botões do jogo

### ISSUE THREAD

**Issue by brunacabeco** [germanodusha/roam#50]
WASD são os botões de movimentação. Além deles, precisamos definir e configurar os outros. Funções abaixo.

- [x] definir botões (são 5)
- Q - KEY GUIDE: abre a tela de key guide
- F - SELECT: seleciona/abre os objetos. 
- E - IGNORE/GO BACK:definir qual botão ignora objetos/volta tela
- I - INFO: definir qual botão abre a tela de infos
- P - PAUSE/END GAME: definir qual botão pausa o jogo

**Comment by guigallo** [comment]
@brunacabeco não entendi esse check de 'configurar'. para configurar aonde?

**Comment by brunacabeco** [comment]
> @brunacabeco não entendi esse check de 'configurar'. para configurar aonde?

Nem eu entendi! Ignora ela.

**Comment by brunacabeco** [comment]
@guigallo reabri a issue porque o botão Q está sendo usado pra ignorar. O E então vai ser o que abre o key guide?
