### ISSUE TITLE
Teste com obj fumaça mais leve

### ISSUE THREAD

**Issue by brunacabeco** [germanodusha/roam#81]
https://drive.google.com/file/d/12-PsuV9Shu9i6Uw1dhzgoXK-cEHTbYM3/view?usp=sharing

**Comment by guigallo** [comment]
usar esfera wireframe, glow branco

**Comment by brunacabeco** [comment]
> usar esfera wireframe, glow branco

Coloquei na descrição aquela fumaça diferente pra gente testar também
