### ISSUE TITLE
[CAPA MEDIA CENTER] Quebra de linha e blur no titulo

### ISSUE THREAD

**Issue by brunacabeco** [germanodusha/roam#97]
- [x] quebra de linha no título
quando o título é muito grande, acontece isso:

<img width="722" alt="Captura de Tela 2021-07-02 às 00 16 57" src="https://user-images.githubusercontent.com/82957414/124275877-7e073900-db19-11eb-917e-d5b0a718e7c1.png">

- [x] colocar blur no título

**Comment by guigallo** [comment]
![image](https://user-images.githubusercontent.com/17219256/124503956-efa2e980-dd9c-11eb-9771-a201f0cbd8ac.png)
